version: 0.0.{build}
image: Visual Studio 2017
dotnet_csproj:
  patch: true
  file: '**\Webserver\PaasEIoT\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
install:
  - ps: Install-Product node "6"
  - cd Webserver\PaasEIoT
  - npm install  
before_build:
  - cd ../
#  - npm install
  - nuget restore
build:
  #publish_wap: true
  publish_azure: true
  verbosity: minimal